### ISSUE TITLE
 ^ Cannot find type [AnyBox.AnyBox]: verify that the assembly containing this type is loaded.

### ISSUE THREAD

**Issue by PaulAnthonyReitz** [dm3ll3n/AnyBox#14]
Getting this error in Visual Studio code and not in Powershell IDE. My Visual Studio code is using 7.0 preview 6. 

Line |
  25 | $userbox = New-Object AnyBox.AnyBox

     |            ^ Cannot find type [AnyBox.AnyBox]: verify that the assembly containing this type is loaded.

**Comment by dm3ll3n** [comment]
AnyBox is not compatible with Powershell Core, “pwsh”.
