### ISSUE TITLE
Docs not found 404

### ISSUE THREAD

**Issue by MtlSnk** [dm3ll3n/AnyBox#23]
Hiya,

Appreciate the work you've done on this module.

The website ([fresh2.dev](https://fresh2.dev)) hosting the documentation seems to either be having issues or has had all its contents removed(?).
If this is intentional is there a way to get a hold of the documentation otherwise. Perhaps it should be added in this repo?

Cheers!

EDIT: for any one looking for docs while it's down, here's the most recent archive: http://web.archive.org/web/20220706151357/https://www.fresh2.dev/doc/anybox/

**Comment by fresh2dev** [comment]
I have been in-between a tricky domain migration, and have perhaps been trying to boil the ocean in my endeavors.

Anyway, it just dawned on me that the source for my old website is still on GitHub, thus the most current docs can be found here:

https://github.com/fresh2dev/clevr.dev/tree/master/content/doc/anybox

Leaving this issue open for transparency.

**Comment by MtlSnk** [comment]
Cheers for the update and good luck with the migration!

I can't reach the repository you linked to, or find it on your profile, is it set to private?

I'd be happy to update the pull request, if you'll agree to place the docs with the source code.

If you'd prefer hosting separately, you could also use GitHub Pages (which should help avoid hosting issues).
Making a repository named "fresh2dev.github.io" and placing the contents of the website in there could possibly work.

Full docs for GitHub Pages are here: https://help.github.com/pages/

**Comment by fresh2dev** [comment]
Thanks. It was private, but is now public.

**Comment by EliorMachlev** [comment]
> Thanks. It was private, but is now public.


Not working:
![image](https://github.com/fresh2dev/AnyBox/assets/26472689/72a37671-9c6f-4a53-aeb5-ae5d4d286ef7)

**Comment by teamcons** [comment]
Hello ! Any news on this ? Is that module still developed as well ?
I would like to get a look at AnyBox ! It looks pretty cool, and im one of the masochists looking to do gui apps with powershell

**Comment by fresh2dev** [comment]
I took down the docs to publish the _new_ docs but kinda lost motivation along the way. There's a ton of unpushed progress (GUI builder, more style options, and apps built with AnyBoc), but the next release also incorporates a pay-what-you-want licensing model, and I haven't had time/motivation to tie up all the loose ends and face the backlash of changing the license, so I've just left this on the backburner while I work on other stuff.

But the idea of AnyBox is simple. Between info posted in the archive link above, and the example code, there is enough to work up a basic app. Maybe some day I'll be motivated and ~~brave~~ dumb enough to publish v1.0.

**Comment by tgill880** [comment]
I just stumbled on `AnyBox`, and it is perfect for my PS scripts. I strongly encourage you to continue!

**Comment by macbrine** [comment]
@fresh2dev Just wanted to chime in and say that I've used AnyBox often over the last year, and that I love it. I would happily donate or pay for a license when/if you set up a way to do so - and I reckon I'm probably not the only one :)

**Comment by PowerPCFan** [comment]
@fresh2dev Just found this and it seems really cool and I'd like to use it, but the docs are still dead and that old GitHub link doesn't work anymore, will this be fixed soon?

**Comment by christopher-conley** [comment]
> @fresh2dev Just found this and it seems really cool and I'd like to use it, but the docs are still dead and that old GitHub link doesn't work anymore, will this be fixed soon?

Docs are in this fork's README here:

https://github.com/MtlSnk/AnyBox

Also at archive.org here:

https://web.archive.org/web/20220701184041/https://www.fresh2.dev/doc/anybox/

And a (now deleted?) how-to blog article on the author's site:

https://web.archive.org/web/20220803134631/https://www.fresh2.dev/anybox-basics/

**Comment by fresh2dev** [comment]
I sincerely appreciate the support and extend my apologies for not addressing this sooner. I spent the better part of the day reviving the docs and getting them deployed here:

https://www.fresh2.dev/r/anybox/v0

**Comment by christopher-conley** [comment]
> I sincerely appreciate the support and extend my apologies for not addressing this sooner. I spent the better part of the day reviving the docs and getting them deployed here:
> 
> https://www.fresh2.dev/r/anybox/v0

What a legend. Thanks!
