### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by LesFerch** [dm3ll3n/AnyBox#27]
Has this project been abandoned?

**Comment by fresh2dev** [comment]
No. It was last updated 6 months ago. There's also many unpushed enhancements. I have many other priorities, and I hope to push this work soon, but AnyBox is fine as it is for the moment, and continues to serve its purpose well.

**Comment by LesFerch** [comment]
Yes, I did see that the last updates were in June. It's [Issue #23](https://github.com/fresh2dev/AnyBox/issues/23), and the lack of response to it, that prompted me to ask the question.

**Comment by fresh2dev** [comment]
My bad. See my comment on https://github.com/fresh2dev/AnyBox/issues/23#issuecomment-1406908094
