### ISSUE TITLE
Default value on set

### ISSUE THREAD

**Issue by kalivodv** [dm3ll3n/AnyBox#3]
Hi Donald,

I would like to thank you for AnyBox module, it's really great 👍 and I have decided to use it in one of my projects :)

Still, I am experiencing one issue. If I try to set parameter `-DefaultValue` together with `-ValidateSet` and `-ShowSetAs ComboBox`, I am not getting the default value. With `-ShowSetAs Radio`, default value is working as expected.

```powershell
$prompts = @(
        
            (New-AnyBoxPrompt -InputType Text -Message 'Username'),
            (New-AnyBoxPrompt -ValidateSet @('group1', 'group2', 'group3') -ShowSetAs ComboBox -DefaultValue 'group2' -Message 'Group'),
            (New-AnyBoxPrompt -ValidateSet @('5 GB', '10 GB') -ShowSetAs Radio -DefaultValue '10 GB' -Message 'Quota')
)

$buttons = @(

            'Save',
            'Quit'
            
)

$answer = Show-AnyBox -Title 'New User' -Prompts $prompts -Buttons $buttons
```

![image](https://user-images.githubusercontent.com/42011316/43766528-f145c574-9a32-11e8-8a6e-36a1862a0816.png)

Could you please help me with this issue?

Regards
Viktor

**Comment by kalivodv** [comment]
Unfortunately, I wasn't able to solve this. But I found temporary solution.
As workaround: 

- I have added index numbers to every object in all of my arrays
- changed one line in `Show-AnyBox.ps1` that seems to be problematic - under `if ($prmpt.ShowSetAs -eq [AnyBox.SetPresentation]::ComboBox)`:

```powershell
if ($prmpt.DefaultValue) {
    $inBox.SelectedItem = $prmpt.DefaultValue
}
```

changed to:

```powershell
if ($prmpt.DefaultValue) {
    $inBox.SelectedIndex = $prmpt.DefaultValue
}
```

So the working example now looks like:

```powershell
$groups = @('group1', 'group2', 'group3')
$i = -1
$groupsarray = @()

foreach ($one in $groups){

    $i++
    $groupsobject = New-Object PSobject
    $groupsobject | Add-Member -MemberType NoteProperty -Name Name -Value $one
    $groupsobject | Add-Member -MemberType NoteProperty -Name Nr -Value $i
    $groupsarray += $groupsobject

}

$defaultgroup = "group2"
$defaultgroupindex = ($groupsarray | Where-Object {$_.Name -eq $defaultgroup}).Nr


$prompts = @(
        
            (New-AnyBoxPrompt -InputType Text -Message 'Username'),
            (New-AnyBoxPrompt -ValidateSet $groupsarray.Name -DefaultValue $defaultgroupindex -Message 'Group'),
            (New-AnyBoxPrompt -ValidateSet @('5 GB', '10 GB') -ShowSetAs Radio -DefaultValue '10 GB' -Message 'Quota')
)

$buttons = @(

            'Save',
            'Quit'
            
)

$answer = Show-AnyBox -Title 'New User' -Prompts $prompts -Buttons $buttons
```

![image](https://user-images.githubusercontent.com/42011316/44095741-d6ba9d22-9fd9-11e8-87ed-4ad73f48f181.png)


I know it's crazy a bit, but I was really hopeless 😃 

Viktor

**Comment by dm3ll3n** [comment]
Viktor, thank you for bringing this to my attention. This bug has been fixed in the 'dev-master' branch and will soon be merged into 'master'.

c5a668aa4cef044e73ded5d48a9db53bdf3e486f
