### ISSUE TITLE
incomplete list of command using get-command -module AnyBox

### ISSUE THREAD

**Issue by Tonic8** [dm3ll3n/AnyBox#7]
Hello

after installing the module, it appear that the command get-command give an incomplete list:

`PS C:\> get-command -module AnyBox

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Show-AnyBox                                        0.3.1      AnyBox`

if we do, we got mode command but the version and source is empty
`PS C:\> get-command *box*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        New-AnyBoxButton
Function        New-AnyBoxPrompt
Function        Show-AnyBox                                        0.3.1      AnyBox`

:) not cool when trying to see what are the commands used by the module.

one more thing:
I had PSCX module, when i first execute "Install-Module -Name AnyBox" it blocked because there is a conflict on the function ConvertTo-Base64, PSCX had a function with the same name.

after removing it  i can install anybox module.

thanks for the work done.
Tonic8

**Comment by dm3ll3n** [comment]
Tonic8, this should be resolved in the latest version. Also, `ConvertTo-Base64` is now `Get-Base64`. Thanks for bringing that to my attention. Let me know if any issues persist.
