### ISSUE TITLE
Resize the Form messes up tab groups

### ISSUE THREAD

**Issue by err-unknown-username** [dm3ll3n/AnyBox#8]
you can see similar in the example process killer app -- resize it and the data grid snaps to take on the bottom half of the form

**Comment by dm3ll3n** [comment]
Resolved in v0.3.4, published to the PSGallery yesterday. Thanks for bringing this up!

Commit: https://github.com/dm3ll3n/AnyBox/commit/7bb70f735fac66478c166cd9e9688b1a447b3a1b
